model: mlp

# datasets
data_path: datasets/IN
class_labels: ["angry", "fear", "happy", "neutral", "sad", "surprise"]  # 6_category


# features
feature_folder: features/6_category/IN/  # saving folder

# checkpoints
checkpoint_path: checkpoints/ 
checkpoint_name: MLP_IN

# model parameters
params: {
  hidden_layer_sizes: [50, 50],
  alpha: 1.9,
  max_iter: 700
}
